#!/usr/bin/env bash
# Converts data/raw/hydrant_density.geojson into hydrant_density.pmtiles.
# Polygon recipe per R3.3 (tippecanoe Flag Reference), adapted for a
# 38-feature Manhattan-only NTA dataset (see data/raw/hydrant_density.geojson,
# generated by scripts/parquet_to_geojson.py from PP2's output).
set -euo pipefail

tippecanoe \
  -o hydrant_density.pmtiles \
  -l hydrant_density \
  -Z10 -z14 \
  --detect-shared-borders \
  --coalesce-densest-as-needed \
  --simplification=2 \
  --include=ntaname \
  --include=hydrant_count \
  --include=density_per_km2 \
  --include=coverage_pct \
  --use-attribute-for-id=gid \
  -f \
  data/raw/hydrant_density.geojson
